version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: sqlc-test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor123
    ports:
      - "5432:5432"
      
  adminer:
    image: adminer:latest
    container_name: my-adminer
    ports:
      - "8080:8080"
